tarea_empresa:
  description: >
    Decidiste {topic}. Esperas ver las reacciones el mercado en general.
  expected_output: >
    Confirmación de {topic}
  agent: empresa

tarea_consumidor:
  description: >
    Evaluas si seguiras comprando en Unautos ante {topic}, debes tomar una sola desición lo más certera posible ya que se realiza con cifras exactas.
    Analizas los efectos de {topic} y miras como afecta esta decisión a tu presupuesto, disponibilidad y calidad del producto.
  expected_output: >
    La decisión del consumidor ante {topic} en un texto.
  agent: consumidor
  input:
    argument: "{{topic}}"

tarea_estado:
  description: >
    Determina si se debe intervenir ante {topic} de Unautos, es decir, aumentar, mantener o disminuir los 
    impuestos a la empresa. Debes tomar una sola decisión objetiva, que no sea ambigua ni que dependa de otros factores.
    Analizar si {topic} afectará negativamente a los consumidores y la estabilidad económica.
  expected_output: >
    Desición sobre la intervención o no intervención, con justificación concisa.
  agent: estado
  input:
    argument: "{{topic}}"



tarea_inversor:
  description: >
    Evalua si es viable proveer capital a Unautos despues de {topic}, debe tomar una decisión objetiva y certera.
    Estimar el riesgo de pérdida de mercado y disminución de ingresos.
    Tomar una decisión clara y definitiva: ¿seguir invirtiendo en Unautos, sí o no? Justifica con argumentos financieros y estratégicos
  expected_output: >
    Decisión sobre el financiamiento de la empresa Unautos
  agent: inversores
  input:
    argument: "{{topic}}"


tarea_analista_de_crecimiento:
  description: >
    Estima cual será el crecimiento aproximado de Unautos despues de {topic}, debe otogar una descripción acerca de cual 
    será su posición en el mercado respecto a otros competidores. Debe ser claro a la hora de explicar por que se da un 
    aumento o disminución en el crecimiento de la empresa, puede apoyarse de herramientas matemátivcas para realizar 
    cálculos pero debe integrar análisis de datos matemáticos con las demás características del mercado como una 
    proyección de la posible oferta y demanda en el mercado
  input:
    argument: "{{topic}}"

  expected_output: >
    Proyección del posible crecimiento de la empresa en el período de tiempo correspondiente y su posición frente a 
    competidores dentro del mercado. Entrega una descripción del posible crecimiento de la empresa teniendo en cuenta 
    los datos proporcionados en {topic}, e integrandolos con proyeciones de las posibles reacciones en el mercado, 
    principalmente en aspectos como la oferta y la demanda.

  agent: analista_de_crecimiento

tarea_escritor:
  description : >
    Recoge todos los textos de los agentes y guárdalas en un archivo"
  
  expected_output: >
    Texto consolidado de los agentes almacenado en un archivo .txt, además pone el titulo del agente correspondiente al texto

  agent: escritor

