tarea_empresa:
  description: >
    Decidiste {topic}. Esperas ver las reacciones el mercado en general.
  expected_output: >
    Confirmación de {topic}
  agent: empresa

tarea_consumidor:
  description: >
    Evaluas si seguiras comprando en Unautos ante {topic}
  expected_output: >
    La decisión del consumidor ante {topic}
  agent: consumidor

tarea_estado:
  description: >
    Determina si se debe intervenir ante {topic} de Unautos, es decir, aumentar, mantener o disminuir los 
    impuestos a la empresa.
  expected_output: >
    Desición sobre la intervención o no intervención, con justificación reducida y concisa.
  agent: estado

tarea_inversor:
  description: >
    Evalua si es viable proveer capital a Unautos despues de {topic}
  expected_output: >
    Decisión sobre el financiamiento de la empresa Unautos
  agent: inversores